//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databinding_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werknemer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Werknemer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int WerknemerID { get; set; }
        public string Achternaam { get; set; }
        public string Voornaam { get; set; }
        public string Functie { get; set; }
        public string Beleefdheidstitel { get; set; }
        public Nullable<System.DateTime> Geboortedatum { get; set; }
        public Nullable<System.DateTime> In_dienst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
